sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 111111
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t9oWk5MGnrJ1tZJCF87
    access-key-secret: AWXqEyg0l5WuOPHmrbeCN1q8OGeWrp
    bucket-name: wytwork